services:
  app1:
    build: .
    container_name: app1
    ports:
      - "3000:3000"
    environment:
      - SERVER=app1
      - PORT=3000
  app2:
    build: .
    container_name: app2
    ports:
      - "3001:3000"
    environment:
      - SERVER=app2
      - PORT=3001
